cmake_minimum_required(VERSION 3.16)
project(mito_unpack LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(TIFF REQUIRED)
find_package(LibXml2 REQUIRED)
find_package(ZLIB REQUIRED)
find_package(OpenMP REQUIRED)
add_executable(mito_unpack src/mito_unpack.cpp)
target_link_libraries(mito_unpack PRIVATE TIFF::TIFF LibXml2::LibXml2 ZLIB::ZLIB OpenMP::OpenMP_CXX)
target_compile_options(mito_unpack PRIVATE -Wall -Wextra -Wpedantic)
